# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hi_jim' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hi_jim

end

target 'hi_jim Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hi_jim Watch App

  target 'hi_jim Watch AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hi_jim Watch AppUITests' do
    # Pods for testing
  end

end
